### ISSUE TITLE
[BUG] Search results for News shows duplicates

### ISSUE THREAD

**Issue by Garfield96** [TUM-Dev/campus_flutter#200]
**Describe the bug**
Search results for news shows duplicates (see screenshot).

**To Reproduce**
1. Go to "Search"
2. Search for "test"
3. Click "Show more" for news
4. See duplicates

**Expected behavior**
No duplicates.

**Screenshots**
<img src="https://github.com/TUM-Dev/campus_flutter/assets/15248220/996c31ad-1b73-4901-b337-e10241490e91" width="300" />

**Smartphone (please complete the following information):**
* Phone: Redmi Note 12 Pro+
* OS version: Android 13 TP1A.220624.014
* Language: German

**Additional context**
N/A

**Comment by jakobkoerber** [comment]
Thanks for reporting this! This "bug" exists due to multiple (faculty) news outlets reporting the same news article. I added a primitive check for duplicate titles :)
