### ISSUE TITLE
[BUG] "Could not find a file named "pubspec.yaml" in https://github.com/jakobkoerber/xml2json.git" when running `flutter pub get`

### ISSUE THREAD

**Issue by nilsreichardt** [TUM-Dev/campus_flutter#204]
**Describe the bug**

I'm not able to run `flutter pub get` in the repository. I'm getting:

```
$ flutter pub get
Resolving dependencies... (9.8s)
Could not find a file named "pubspec.yaml" in https://github.com/jakobkoerber/xml2json.git 1c1b397652b5806bf2e04333139bb9d3282fe630.
```

**To Reproduce**
1. Clone this repository
2. Navigate to the folder
3. Run `flutter pub get`

**Expected behavior**
I should be able to get the packages without any errors.

**Screenshots**

<img width="1410" alt="image" src="https://github.com/TUM-Dev/campus_flutter/assets/24459435/31791445-04da-481a-8370-49eff3741ba8">

https://github.com/jakobkoerber/xml2json/commit/1c1b397652b5806bf2e04333139bb9d3282fe630

**Additional context**

```
Flutter 3.16.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 78666c8dc5 (5 weeks ago) • 2023-12-19 16:14:14 -0800
Engine • revision 3f3e560236
Tools • Dart 3.2.3 • DevTools 2.28.4
```

**Comment by jakobkoerber** [comment]
this issue will be mitigated with #201 as I am currently working on the fork. my mistake though to delete the prior changes 😅
