### ISSUE TITLE
[BUG] Fetching meal plan doesn't work

### ISSUE THREAD

**Issue by nilsreichardt** [TUM-Dev/campus_flutter#206]
![Screenshot_20240126-100255.png](https://github.com/TUM-Dev/campus_flutter/assets/24459435/fe5b14c1-66b7-4058-8c67-45decf0063a6)

For every location the meal can not be fetched. Not sure if it's a bug of the app.

**Comment by jakobkoerber** [comment]
Thanks for reporting this! It's fixed in #201
