### ISSUE TITLE
[BUG] Loading of Profile Details Fails

### ISSUE THREAD

**Issue by GunniBusch** [TUM-Dev/campus_flutter#213]
**Describe the bug**
The profile badge on the main side is not loading.
I think there is something wrong with the api. I put screenshots form the request. But fyi, if I put the id of an other student it worked.
**To Reproduce**
1. Go to the main page of the app/web app
2. See profile badge not loading

**Expected behavior**
To show the user its profile picture and name I guess.

**Screenshots**
![IMG_1945](https://github.com/TUM-Dev/campus_flutter/assets/47161699/474eb9a1-786c-4d2a-ba42-c2ef66a19fc4)
![IMG_1947](https://github.com/TUM-Dev/campus_flutter/assets/47161699/a2bfaa16-2774-46f1-8a1f-06be3df8607d)
![IMG_1946](https://github.com/TUM-Dev/campus_flutter/assets/47161699/77b87398-3118-47a0-9f20-f673cd0fe5c6)

**Smartphone (please complete the following information):**
* Phone: 15 pro
* OS version: 17.4
* Language: de

**Additional context**

**Comment by jakobkoerber** [comment]
Thanks for contributing! Seems like something I have to escalate to the TUMonline team since your `personenDetails` returns a 404

**Comment by GunniBusch** [comment]
> Thanks for contributing! Seems like something I have to escalate to the TUMonline team since your `personenDetails` returns a 404

Thanks, keep me posted.

**Comment by jakobkoerber** [comment]
They know now about the issue and will investigate further, probably tomorrow. This is an issue with TUMonline and can't be solved in the Frontend. I improved however the way the UI handles the issue. This will be released with `4.5.2`

**Comment by jakobkoerber** [comment]
Was successfully fixed by the TUMonline team 👌 You should now be able to see your full contact card and, if an error occurs, a better handled UI with 4.5.2

**Comment by GunniBusch** [comment]
> Was successfully fixed by the TUMonline team 👌 You should now be able to see your full contact card and, if an error occurs, a better handled UI with `4.5.2`. Please keep in mind that due to caching the new data might not be visible immediately

Works. Thx
