### ISSUE TITLE
[BUG] App keeps forgetting the registered Tokens & Login

### ISSUE THREAD

**Issue by JustusvonderBeek** [TUM-Dev/campus_flutter#214]
**Description**
I've used the app a few times in the last weeks and it keeps forgetting that I already created and activated a token. Suddenly I'm logged out again without any user action and have to create and activate a new token. I did not use the logout button nor performed any other action. The tokens are still valid and activated in the Campus Website.

**To Reproduce**
Unfortunately I'm not sure what exactly is causing this issue. After roughly a week of inactivity I need to login again and have to create and activate a new token.

**Expected behavior**
Either stay logged in or reuse the existing token after login.

**Smartphone:**
* Phone: Xiaomi Mi 9T Pro
* OS version: Android 11 RKQ1 / MIUI 12.5.1
* Language: German

**Comment by jakobkoerber** [comment]
Thanks for contributing! We're already investigating this issue and are hoping to resolve this issue soon
