### ISSUE TITLE
[Discussion] App Layout

### ISSUE THREAD

**Issue by LadnerJonas** [TUM-Dev/campus_flutter#219]
Foremost, thank you for your work!

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I open the app. It feels like the app layout does not follow the most common use case of the app. Personally, I almost exclusively used the old app to lookup the today's menu in the Mensa/Cafeterias. In my case, I would like to see the Mensa Garching + StuBistro Garching.
I used that Mensa widget **every single day, when I was at the uni**. 

Instead, every time I open the app I see my name (great, I know that already) and some personal info.
This is helpful for first-semester students, but I think everybody else knows their TUM email address already. I outlined the start menu elements I use in the last section.

**Describe the solution you'd like**

Let the user configure the start page. The user should be able to choose the most important elements for his/her workflow. 

Furthermore, please re-work the menu page of a given Mensa.
The user has to scroll multiple times towards the right to see every dish. This only utilizes a small area of the screen.

**Describe alternatives you've considered**
Asking users in a form what the most common use cases are. Then when enough high quality data is there, rework the start page to fit most users. 

Personal: writing my own small app, which shows today's/weekly menu for my most frequently used cafeterias.

<img src="https://github.com/TUM-Dev/campus_flutter/assets/92096842/ecc6f68c-5b2b-4712-a6a5-909c33b639b3" width="200px" ></img>

| Color| Reason why I don't use these elements |
|--------|--------|
| red | I never use that feature and I think most of my peers don't use it either |
| green | good if I have not payed the semester fee. After the payment was successful optionally show a notification, when starting the app. After that always hide that element |
| blue | I dont use it, but I can think of use cases where those features are handy | 

**Additional context**
Android 13

**Comment by CommanderStorm** [comment]
Foremost: this type of issue (10-in-one) is incredibly difficult to respond to. It is quite likely that I missed some sub-part.

> every time I open the app I see my name [...] and some personal info.

Actually, these are part of an external requirement.
The reason you are seeing this is that we plan to integrate a digital student card with the features listed under this wiki page (German only): https://collab.dvb.bayern/display/TUMmwncard/MWN+Ausweis+Startseite
@jakobkoerber knows more about the status of this feature (if we have already released the library sub feature or not) ^^

> Let the user configure the start page

This is already in the works, but has not made it to the first release of the flutter campus app:

| <img src="https://github.com/TUM-Dev/campus_flutter/assets/26258709/86789f60-cc08-44b5-9f2e-34077365cf1d" width="200px" ></img> | <img src="https://github.com/TUM-Dev/campus_flutter/assets/26258709/57f6e4aa-0846-4235-9342-19822c7f575e" width="200px" ></img> | <img src="https://github.com/TUM-Dev/campus_flutter/assets/26258709/4f328f67-7611-4e9d-81ba-858284c6fd6f" width="200px" ></img> | <img src="https://github.com/TUM-Dev/campus_flutter/assets/26258709/ac4dbfc7-d521-4873-8360-7eb2ffda83fc" width="200px" ></img> | 
|--------|--------|--------|--------|

> I used that Mensa widget

We decided to at first launch without having the previous widgets, as we believed those were a smaller user base than they apparently are. (or at least said user base is quite vocal…)
To be fair, that decision was a majority vote (some devs wanted to have more “feature parity” while others considered the version we launched better than the old state..)

here is an example of how the newer widgets might look:
<img src="https://github.com/TUM-Dev/campus_flutter/assets/26258709/8f4e5da6-ffa1-471e-8ff0-2059abb12aa4" width="200px" ></img>

> Personal: writing my own small app, which shows today's/weekly menu for my most frequently used cafeterias.

There are already a fair number of apps out there. Have you had a look at improving one of these two apps:
- https://menu.tum.sexy/de
- https://eat-api.tum.sexy/

Being cheeky: If you were to contribute a widget for the campus app, we might be able to integrate this feature faster (and help more students ^^)…

> Asking users in a form what the most common use cases are.

I have a somewhat strong opinion that surveys are not worth anybody's time, and that the data quality you get from them can never be good.

I have written down my thoughts on this matter and an alternative approach in a different repository
https://github.com/louislam/uptime-kuma/issues/4456

**Comment by jakobkoerber** [comment]
I will close this issue for now :) many of your suggestions we're implemented to an extend with version 5.0, like a new meal plan overview and improved home screen customizability. Additionally, we will continue to improve the usability of the new TUM Campus App in the coming versions. But since user workflows are highly subjective and varying we aim for a comprise that helps all of our users. Thanks for your contribution!
