### ISSUE TITLE
[Enhancement] Customizability for Number of Days in Calendar Week View

### ISSUE THREAD

**Issue by Pydes-boop** [TUM-Dev/campus_flutter#235]
**Describe the bug**
The week view in the calendar on mobile only displays 4 days at once (ie. week starts at monday ends at thursday) Swiping from left to right to the next week then makes the next display start at the friday of the same week.

**To Reproduce**
1. Go to Calendar
2. Click on Week View

**Expected behavior**

I want to get an overview of my week (either 5 or 7 days) and be able to scroll through weeks.

**Screenshots**

Week View: 
![image](https://github.com/TUM-Dev/campus_flutter/assets/59734957/601c4962-88aa-4493-933e-157cd9a237ca)

Swiping to the previous week:
![image](https://github.com/TUM-Dev/campus_flutter/assets/59734957/a4f43e5c-6e1f-471a-b857-4e6d3136f7cc)

**Smartphone:**
* Phone: Iphone 13
* OS version: 17.3.1
* Language: English
* App Version: 5.0

**Comment by jakobkoerber** [comment]
Thank you for contributing! While I understand your concern about the number of days displayed in the week view, displaying 4 days on a phone was a conscious decision. During the beta phase of the new TUM Campus App many users gave us the feedback about degraded readability or the lack of weekends while displaying 5 or 7 days respectively at the same time. I completely understand your point about the inconsistent start day of a week and will think about a solution for version 5.0.2 or later, e.g. user customizability in the settings. But for now, showing 4 days on a phone and 7 days on a tablet is the best compromise for all our users.

> [...] be able to scroll through weeks.

This should already be possible with the weeks divided unequally into 4 days

**Comment by Pydes-boop** [comment]
If its supported on a tablet then it should maybe be a config setting somewhere in the app to switch between a weekly view of 4/5/7 day view for users preference. In any case calling the 4-day view a weekly view seems confusing.

While i understand your point about user testing, this deviation is highly atypical to how other major apps and platforms implement calendar views on mobile. Setting the standard to 4 days while most users while expect a 7 or at least 5 day overview from other apps they are used to deviates from the expected standard and kind of destroys the purpose of a weekly view entirely, to have an overview of the the current/next week and weekly events.

It also makes the weekly view way harder to read, typically calendars both analog and digital are all sorted and displayed around starting at certain weekdays (usually mondays or sundays), and this orientation is lost completly in the current view. Similarily your monthly view always starts at a monday, like any calendar would, while the weekly view now starts at differing days depending on which day of the week i open it (with the view also changing 7 times a week). Comparing this to the monthly view one would expect to not loose their point of comparison for following events, every day. If i want a view that changes daily, the daily view already exists.

For the user testing i am curious, did you only test 5/7 days and got that feedback or did you do side-by-side comparisons of 4/5/7 prefer as a weekly view?

**Comment by jakobkoerber** [comment]
> If its supported on a tablet then it should maybe be a config setting somewhere in the app to switch between a weekly view of 4/5/7 day view for users preference. In any case calling the 4-day view a weekly view seems confusing.

Like I mentioned before, we will evaluate all possible solutions and attempt to find the best compromise for _all_ users :) this will probably mean an entry in the settings giving the user the option to show/hide weekends or renaming it to "4-Day View" or similar

> For the user testing i am curious, did you only test 5/7 days and got that feedback or did you do side-by-side comparisons of 4/5/7 prefer as a weekly view?

We had 5 days and 7 days in some versions, no concrete user testing since this is a rather small detail. With 5 days users complained about not seeing the weekends, with 7 days users complained about degraded readability. 4 days seemed like quick fix for the best common ground, but I totally understand your gripes with that

**Comment by Pydes-boop** [comment]
> e.g. user customizability in the settings.

Im sorry, it is late and i totally missed the part in your first answer talking about user customizablity so i tried to provide reasoning towards adding such customizability.

**Comment by jakobkoerber** [comment]
> Im sorry, it is late and i totally missed the part in your first answer talking about user customizablity so i tried to provide reasoning towards adding such customizability.

No worries 😄 I understand your concern and we want to provide the best possible solution for all users. Adding customization should allow that
