### ISSUE TITLE
[BUG]  Android App Crashes with active Calendar Widget

### ISSUE THREAD

**Issue by benjibst** [TUM-Dev/campus_flutter#237]
**The app crashes whenever I start it while the widget is placed on my homescreen on android**

**To Reproduce**
1. Place the TUM Campus widget on the homescreen on an android device
2. Open the campus app

**Expected behavior**
The app doesnt crash

**Smartphone (please complete the following information):**
* Phone: Realme GT 2 Pro and Samsung Galaxy Tab S8
* OS version: Android 14
* Language: German

**Comment by jakobkoerber** [comment]
Thanks for contributing! I'm currently investigating this issue 🙂 seems to be an Android-only bug for which I will try to publish a fix today

**Comment by jakobkoerber** [comment]
Hey @benjibst, could you check again with the latest version on the Google Play Store? I pushed a first attempt to fix the bug you reported 😄

**Comment by benjibst** [comment]
it seems to be working, but there is still another problem. When i have the widget placed, i sporadically get an android pop up message that the tum campus app crashes repeatedly. i dont know if this is related though.

**Comment by jakobkoerber** [comment]
Yes, I observed that too... I'm still working on the final fix 👍 thanks for keeping me updated ^^

**Comment by benjibst** [comment]
I sent an email to app@tum.de!

**Comment by jakobkoerber** [comment]
Thanks! You should have received an invitation or be able to access the internal beta via the link I sent you

**Comment by jakobkoerber** [comment]
Hey @benjibst, any update if the issues still persist with build 1015? Thanks!

**Comment by benjibst** [comment]
Hello, unfortunately i dont know how to see which build is running on my device, but i assume its the most up to date one because there is no update button on the play store. unfortunately the issue is still there for me

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jakobkoerber** [comment]
> unfortunately i dont know how to see which build is running on my device

Did you try to install the internal beta via the link I sent you? And could you provide, if possible, screenshots here in the issue or via app@tum.de of what exactly you see. Thanks a lot!

**Comment by benjibst** [comment]
Yes, it says on the play store that im part of the internal test program. 
There are 2 things:
When i open the app directly, it just automatically closes again
When i tap on the widget, i get a pop up saying that the app repeatedly crashes

![Screenshot_2024-04-06-13-02-48-83_b783bf344239542886fee7b48fa4b892.jpg](https://github.com/TUM-Dev/campus_flutter/assets/76067254/74d351f2-492e-469a-9698-051b715ccc76)

Its hard to reproduce because it happens very inconsistently.
