### ISSUE TITLE
[BUG] Decoding of Calendar Events Fails on Android

### ISSUE THREAD

**Issue by benjibst** [TUM-Dev/campus_flutter#244]
**Describe the bug**
The calendar widget doesn't show any lectures, even though i have 4 lectures today that are displayed in the calendar within the app.

**To Reproduce**
Add the calendar widget to the homescreen of an android device

**Expected behavior**
A list of lectures of the current and following days should be displayed by the widget.

**Screenshots**
![Screenshot_2024-04-15-10-00-34-59_b783bf344239542886fee7b48fa4b892.jpg](https://github.com/TUM-Dev/campus_flutter/assets/76067254/92b21eca-8002-43d0-a0e2-1be463575295)

**Smartphone (please complete the following information):**
* Phone: Realme GT 2 Pro and Samsung Galaxy Tab S8
* OS version: Android 14
* Language: German

**Comment by jakobkoerber** [comment]
I'm still investigating this... this is really hard to reproduce on Android since everybody uses different devices and Android distribution. Which campus app version are you currently using? And do still experience crashes or just an empty widget?

**Comment by Marlene163** [comment]
I have the same problem (on OnePlus Nord CE 5G: Android 12 and Samsung Tab 8: Android 14)

**Comment by jakobkoerber** [comment]
@benjibst please download the latest internal beta version (5.0.3 Build 1017) and test if the issues still persist... I invested a lot of time attempting to debug the issue 😅 hopefully it is now resolved

**Comment by CommanderStorm** [comment]
> please download the latest internal beta version

No such beta exists on my device. Is this expected?
(I am asking because https://github.com/TUM-Dev/campus_flutter/pull/246/commits/23367be54e756d57d3ebf229f6e88275386a6372 had some build errors)

**Comment by benjibst** [comment]
> @benjibst please download the latest internal beta version (5.0.3 Build 1017) and test if the issues still persist... I invested a lot of time attempting to debug the issue 😅 hopefully it is now resolved

Hello Jakob,
Unfortunately the issue persists on my device:( the calendar widget still doesnt show any events and when i open the app with the widget placed, it always crashes.

**Comment by jakobkoerber** [comment]
> > please download the latest internal beta version
> 
> 
> 
> No such beta exists on my device. Is this expected?
> 
> (I am asking because https://github.com/TUM-Dev/campus_flutter/pull/246/commits/23367be54e756d57d3ebf229f6e88275386a6372 had some build errors)

I think you're not part of the internal beta track (yet) 😄

**Comment by jakobkoerber** [comment]
> > @benjibst please download the latest internal beta version (5.0.3 Build 1017) and test if the issues still persist... I invested a lot of time attempting to debug the issue 😅 hopefully it is now resolved
> 
> Hello Jakob,
> Unfortunately the issue persists on my device:( the calendar widget still doesnt show any events and when i open the app with the widget placed, it always crashes.

That's really frustrating, since it takes a lot of time to even reproduce such issues 🙃 could you confirm the version and build number for me, by navigating to the settings within the app? Did you try to re-install the app at some point? And would you be willing to provide me with your TUM ID, e.g. via app@tum.de? I would like to request a token for further debugging, activating the calendar permission should be sufficient :)

**Comment by benjibst** [comment]
Yes, i confirm i have build 1017 installed on my device
![Screenshot_2024-04-21-09-18-16-19_6e0b122dca11de86c8dd96dbad655ddf.jpg](https://github.com/TUM-Dev/campus_flutter/assets/76067254/d58528ac-117e-48c2-8e09-81dc7993a53f)

Also, the issue persists after reinstalling the application, if anything it got worse because now it crashes even without the widget.

My tum id is go73nej

**Comment by jakobkoerber** [comment]
@benjibst I rewrote a lot of things in the Android widget and published them as an internal beta with 5.0.3 (1018), please delete the app, download the latest version and see if the issue still persists 😅 thanks a lot for your help!

**Comment by benjibst** [comment]
> @benjibst I rewrote a lot of things in the Android widget and published them as an internal beta with 5.0.3 (1018), please delete the app, download the latest version and see if the issue still persists 😅 thanks a lot for your help!

Hello Jakob, downloaded the new build, it seems to work now! Thank you!

**Comment by jakobkoerber** [comment]
That's great to hear! I hope it stays that way 😄 thanks for your cooperation and patience!

**Comment by benjibst** [comment]
Another thing that would be nice, to make the widget more useful: To show when an event is due, use the day name and day number within month, instead of day number and month name. 
Like in the google calendar widget for example. Since i believe the widget is used mainly to look up appointments within a given day or the next few days, i think this would be useful. Otherwise you have to do the maths in your head.
![Screenshot_2024-04-21-15-55-34-15_b783bf344239542886fee7b48fa4b892.jpg](https://github.com/TUM-Dev/campus_flutter/assets/76067254/7266d26a-db69-4c6e-8ccf-845fd49a5d35)

Added a screenshot of how this looks in the google calendar widget
