### ISSUE TITLE
[Enhancement] Display Cancelled Events More Intuitively

### ISSUE THREAD

**Issue by benjibst** [TUM-Dev/campus_flutter#245]
**Describe the bug**
The campus app shows me a lecture today that doesn't exist in TumOnline.

**To Reproduce**
1. For me this happens for the course "Computational intelligence"

**Expected behavior**
The campus app calendar should match the official calendar in TumOnline

**Screenshots**
![Screenshot_2024-04-15-10-56-48-72_6e0b122dca11de86c8dd96dbad655ddf.jpg](https://github.com/TUM-Dev/campus_flutter/assets/76067254/ba084222-836a-478a-b808-0289945cdcb9)

![Screenshot_2024-04-15-10-56-59-88_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/TUM-Dev/campus_flutter/assets/76067254/ea2556b5-50f4-43d4-b214-459d47e95e1b)

**Comment by jakobkoerber** [comment]
Seems to be a cancelled event which is still provided by the endpoint :) I will change the calendar accordingly
