### ISSUE TITLE
[Enhancement] Directions in Room Finder View

### ISSUE THREAD

**Issue by jakobkoerber** [TUM-Dev/campus_flutter#247]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by CommanderStorm** [comment]
@jakobkoerber in case you mean end-to end directions: that is a far-future feature of the roomfinder (lots of steping stones before we can get there)

Opening the coordinates in a maps app might be an intermediate option until we get there.
