### ISSUE TITLE
[Enhancement] Nudge Users to Log In

### ISSUE THREAD

**Issue by CommanderStorm** [TUM-Dev/campus_flutter#248]
**Is your feature request related to a problem? Please describe.**
Currently, when a user is not logged in (f.ex. via skipping auth), they get "Token invalid" errors on the screens which require a token.
I think it might be more user-friendly to show a login message instead.

**Describe the solution you'd like**
We likely should order another illustration for this.
What are you peoples ideas?

**Describe alternatives you've considered**
Just display a plain "this view can only be displayed if you log in"->"Log in" message

**Additional context**
From feedback of users via the feedback chanel ^^

**Comment by jakobkoerber** [comment]
Like so? 😄

![image](https://github.com/TUM-Dev/campus_flutter/assets/56073945/78730e68-a43e-40ff-b415-99253393c579)

**Comment by CommanderStorm** [comment]
Looks good to me as an inital one.
Maybe bit bigger "login needed" with larger bottom padding and adding the [text-wrap: balanced](https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap) equivalent to the second one to make this feel more "centered" (all just a feeling).

Think that ordering another illustration might be beneficial as this is not an error => not 1 picture for everything
Do you have any ideas what should be on said illustration?

**Comment by CommanderStorm** [comment]
Maybe also relevant:
How does the dashboard/frontpage/leftmost page look?
Can we add a login button there too or would this be too crowded?

**Comment by jakobkoerber** [comment]
> Maybe also relevant: How does the dashboard/frontpage/leftmost page look? Can we add a login button there too or would this be too crowded?

This would be way too crowded in my opinion 😅

**Comment by CommanderStorm** [comment]
Maybe clicking on where we display the name if logged in could redirect to the login page, but likely the above approach is good enough.
