### ISSUE TITLE
[Support] Login Process Unclear

### ISSUE THREAD

**Issue by justchokingaround** [TUM-Dev/campus_flutter#250]
**Describe the bug**
I can't login

**Additional context**
I am not sure where the token for logging in can be found, iirc it used to be on tumonline, but I can't find it there anymore. Could you please help me out?

**Comment by jakobkoerber** [comment]
Hey! Could you specify your current workflow and where exactly you got stuck?

**Comment by justchokingaround** [comment]
Hi, sure, I was using the app around a year ago I think, then I deleted it. Now I've reinstalled it and it basically says "Not Logged In" and if I go to a section that requires a token, it says "Token Invalid Try creating a new token!". 

Sorry that I skipped the stuff in the template, I thought it was irrelevant to the issue, I will answer any questions that you have

**Comment by jakobkoerber** [comment]
> Hi, sure, I was using the app around a year ago I think, then I deleted it. Now I've reinstalled it and it basically says "Not Logged In" and if I go to a section that requires a token, it says "Token Invalid Try creating a new token!".
> 
> Sorry that I skipped the stuff in the template, I thought it was irrelevant to the issue, I will answer any questions that you have

So you were never greeted with the login mask? You can find the login via at the bottom of the settings (menu icon in the top left corner) by pressing "Reset All" (we will improve this with 5.0.3)

**Comment by justchokingaround** [comment]
I wasn't. After reseting everything works after I followed the instructions. Thank you!

**Comment by jakobkoerber** [comment]
> I wasn't. After reseting everything works after I followed the instructions. Thank you!

Interesting, I presume you are using TUM Campus App on Android?

**Comment by justchokingaround** [comment]
yep
