### ISSUE TITLE
[Enhancement] Display Study Room Utilization Percentages using IRIS

### ISSUE THREAD

**Issue by AntonMC-Github** [TUM-Dev/campus_flutter#288]
**Is your feature request related to a problem? Please describe.**
Currently the Lernräume are already shown. The problem is, that rooms, where occupancy is determined via WIFI and thus provided as percentages, the APP can't handle that. Thus the room status is currently shown in App as unknown.

**Describe the solution you'd like**
The used IRIS API also sends out the utilization percentages as "percent". Using this datapoint, we can simply show this Percentage and color the percentage based on whether the percentage is above x percent (e.g. 0-50%: green, 51-75%: yellow, 76-100%: red)

**Describe alternatives you've considered**
- Leaving it like it currently is -> Not very helpful
- Using the percentage but showing it as "belegt" or "frei" based on whether the percentage is above x percent -> We have the data, we can also show it openly.

**Comment by jakobkoerber** [comment]
Hey @AntonMC-Github, thanks for your suggestion! 😄 We can happily integrate that. One question: which API/Endpoint are you talking about? )I'm not able to read out percentages using https://www.devapp.it.tum.de/iris/ris_api.php?format=json 🤔
