### ISSUE TITLE
[Enhancement] Student Card Preview on Home Screen Should Use Profile Picture

### ISSUE THREAD

**Issue by alexanderstephan** [TUM-Dev/campus_flutter#296]
**Is your feature request related to a problem? Please describe.**

Although we have a picture for each student's profile, we don't show it in the preview on the home screen.

**Describe the solution you'd like**

When I click on my profile, I get to the digital student card, which also shows my profile picture. 
<img src="https://github.com/user-attachments/assets/22d4f2ec-38fb-4303-9662-d630ffe29d65" width=50% height=50%>

I would also expect this picture to show here in this avatar.

<img src="https://github.com/user-attachments/assets/cae9735f-e9cf-404c-8e5e-ff5019711acd" width=50% height=50%>

**Describe alternatives you've considered**

Maybe this was done on purpose, as some people don't like their picture. If that is the case, I can understand it. But maybe then there could be an option to disable this profile picture preview or the addition of an option to change the picture in the app.

**Comment by Cacaonut** [comment]
> Maybe this was done on purpose, as some people don't like their picture. If that is the case, I can understand it. But maybe then there could be an option to disable this profile picture preview or the addition of an option to change the picture in the app.

Would this be possible to do? Particularly, an option to switch to the business card picture as it was before would be best.
Seeing my student card picture upon launching the app kind of feels like accidentally opening the selfie camera when unlocking my phone. 😬

**Comment by jakobkoerber** [comment]
> Particularly, an option to switch to the business card picture as it was before would be best

Hey @Cacaonut, thank you for your message! I think this is very controversial and there's no perfect option. On the one hand, letting the user choose between their often nicer business card picture and their student card picture seems like a good option, but on the other hand, the mini student card on the home screen represents a button to the full student card. It would be consistent to show the same information. Adding an option to let the user choose is pretty straightforward, I'm just not sure it's the best way to go.
